INSERT INTO users (username, password, enabled) VALUES ('user@mail.com', '$2a$10$wPHxwfsfTnOJAdgYcerBt.utdAvC24B/DWfuXfzKBSDHO0etB1ica', TRUE);
INSERT INTO users (username, password, enabled) VALUES ('admin@mail.com', '$2a$10$wPHxwfsfTnOJAdgYcerBt.utdAvC24B/DWfuXfzKBSDHO0etB1ica', TRUE);

INSERT INTO users (username, password, enabled) VALUES ('novi@mail.com', '$2a$10$wPHxwfsfTnOJAdgYcerBt.utdAvC24B/DWfuXfzKBSDHO0etB1ica', TRUE);
INSERT INTO users (username, password, enabled) VALUES ('hendrikjan@mail.com', '$2a$10$wPHxwfsfTnOJAdgYcerBt.utdAvC24B/DWfuXfzKBSDHO0etB1ica', TRUE);

INSERT INTO authorities (username, authority) VALUES ('user@mail.com', 'ROLE_USER');
INSERT INTO authorities (username, authority) VALUES ('hendrikjan@mail.com', 'ROLE_USER');
INSERT INTO authorities (username, authority) VALUES ('admin@mail.com', 'ROLE_USER');
INSERT INTO authorities (username, authority) VALUES ('admin@mail.com', 'ROLE_ADMIN');

INSERT INTO authorities (username, authority) VALUES ('novi@mail.com', 'ROLE_USER');
INSERT INTO authorities (username, authority) VALUES ('novi@mail.com', 'ROLE_ADMIN');



INSERT INTO plants (id, description, care, potting, difficulty, file_name, food, latin_name, light, location, name, uploaded_by_username, uploaded_date, watering)
VALUES ('1001',  'Bijzonder fraaie bladplant. De diverse soorten hebben grote, veelkleurige bladeren met vele verschillende opvallende tekeningen en patronen.','Het beste staan calathea’s in vrij vochtige, maar beslist niet natte grond. Dat bereik je het gemakkelijkste door gelijkmatig en regelmatig water te geven, telkens in kleine beetjes tegelijk.','Je Calathea zal goed groeien in een luchtige, waterdoorlatende potgrond. Gebruik hiervoor een specifieke potgrond voor kamerplanten. Plaats je Calathea bij voorkeur direct na aankoop in een pot. De wortels zitten namelijk heel krap in hun pot en hebben nauwelijks plaats om te groeien. We raden je aan om de plant om de 2 jaar te verpotten, idealiter in het voorjaar.', 'HARD', 'Calathea.jpeg', 'MONTH', 'Calathea', 'HALFSUNNY', 'uploads/Calathea.jpeg', 'Pauwenplant', 'novi@mail.com', '2021-10-01 11:21:44.084', 'WEEK');
INSERT INTO Plants (id, description, care, potting, difficulty, file_name, food, latin_name, light, location, name, uploaded_by_username, uploaded_date, watering)
VALUES ('1002',  'Behoort ook tot de groep luchtzuiverende planten. De naam Drakenbloedboom heeft een Dracaena te danken aan zijn uiterlijk, met puntige bladeren en rode hars, die bij sommige Dracaena''s vrijkomt.','De Dracaena is een makkelijke kamerplant om te verzorgen. De Dracaena kan goed op een plek staan in de (half)schaduw. Ook verbruikt de Drakenbloedboom weinig water.', 'Plaats hem in een pot die minimaal 20% breder is en gebruik normale potgrond. Een grotere plantenbak stimuleert de groei, verhoogd de gezondheid van de plant en creëert een grotere waterbuffer. Hiernaast heeft de plant de beschikking over meer voedingsstoffen. Gebruik geen hydrokorrels op de bodem. Het stilstaande water, wat zich daartussen verzameld, is minder makkelijk te bereiken door de wortels en gaat rotten.','EASY', 'DrakenBloedboom.jpeg', 'MONTH', 'Dracacena', 'SHADOW', 'uploads/DrakenBloedboom.jpeg', 'Drakenbloedboom', 'admin', '2021-10-01 11:30:44.084', 'WEEK');
INSERT INTO Plants (id, description, care, potting, difficulty, file_name, food, latin_name, light, location, name, uploaded_by_username, uploaded_date, watering)
VALUES ('1003',  'Kent vele verschillende soorten met prachtige bladeren, ieder met zijn eigen kleur, vorm en tekening. Geef jouw Peperomia een plekje waar deze veel licht krijgt.', 'De grond mag net niet uitdrogen, maar zeker ook niet te nat zijn, want daar kan hij slecht tegen. Vanaf het najaar minderen met water geven, tot zo’n 1 keer per week. In de lente en zomer heeft de plant voeding nodig.','De peperomia is geen snelle groeier! Het is daarom waarschijnlijk meer dan genoeg om de plant eens in de drie jaar te verpotten. De potgrond verliest langzaam de luchtige structuur, dus met nieuwe potgrond zitten de wortels er weer lekker luchtig bij. Er zijn twee manieren om de Peperomia kan stekken en dan kan je ze nog stekken in water of in de grond. Het is even zoeken wat voor jouw plant het beste werk, als je dit eenmaal weet gaat het vrij gemakkelijk.', 'EASY', 'peperomia.jpg', 'MONTH', 'Peperomia', 'HALFSUNNY', 'uploads/peperomia.jpg', 'Peperomia', 'user', '2021-10-01 11:31:44.084', 'WEEK');

INSERT INTO Plants (id, description, care, potting, difficulty, file_name, food, latin_name, light, location, name, uploaded_by_username, uploaded_date, watering)
VALUES ('1004',  'Met zijn ronde blaadjes, is de Pannenkoekplant een bijzondere verschijning. Het is ook een luchtzuiverende plant!','De plant staat het liefst op een plek met veel indirect zonlicht. De plant krijgt verder het liefst regelmatig kleine scheutjes water, zodat de grond lichtvochtig blijft.','Verpot de plant eens in de twee jaar. Kies hierbij voor een pot die minimaal 20% groter is dan de huidige pot. Het stekken van je Pannenkoekenplantje heel makkelijk. Er groeien kleine kindjes rondom de moederplant. Deze kun je het beste even laten zitten zodat ze iets groter zijn. Vervolgens kun je ze voorzichtig los snijden en in een glas met water zetten. Ververs het water regelmatig totdat zich wortels vormen. Als het stekje worteltjes heeft, kun je hem in verse grond plaatsen.', 'EASY', 'pannenkoekplant1.jpg', 'MONTH', 'Pilea Peperomioides', 'HALFSUNNY', 'uploads/pannenkoekplant1.jpg', 'Pannenkoekplant', 'novi@mail.com', '2021-10-01 11:31:44.084', 'THREEDAYS');
INSERT INTO Plants (id, description, care, potting, difficulty, file_name, food, latin_name, light, location, name, uploaded_by_username, uploaded_date, watering)
VALUES ('1005',  'Om de verdamping te beperken en luchtvocht op te nemen is het blad bedekt met een grijswit viltig laagje. Dit mag nooit worden afgeveegd!','Hij houdt er wel van om continue licht vochtige aarde te hebben, dus let daar op. Hij staat het liefste op een lichte plaats waar geen direct zonlicht staat.','Maak een bakje klaar dat minstens 5 cm breder is dan de originele bak. Als u een draadmand gebruikt, bekleed de mand dan met ongeveer 2,5 cm vochtig, stevig verpakt veenmos (laat het mos eerst drie of vier uur in een kom of emmer weken).
Vul de mand (of een gewone pot) voor ongeveer de helft met een los, goed gedraineerd, poreus potmengsel: bij voorkeur zoiets als geraspte pijnboomschors, veenmos of een soortgelijk medium. U kunt maximaal een derde van de gewone potmix gebruiken.
', 'MODERATE', 'Platycerium.jpg', 'MONTH', 'Platycerium', 'HALFSUNNY', 'uploads/Platycerium.jpg', 'Hertshoornvaren', 'novi@mail.com', '2021-10-10 11:33:44.084', 'TWODAYS');
INSERT INTO Plants (id, description, care, potting, difficulty, file_name, food, latin_name, light, location, name, uploaded_by_username, uploaded_date, watering)
VALUES ('1006',  'De bladeren lijken van fluweel, met hun kleine felgekleurde haartjes.','En deze Indonesische lichtaanbidder laat direct zien hoe blij ze is met veel (indirect) zonlicht. Geef regelmatig kleine beetjes water.','Voorzie de plant elke 2 jaar van een laag nieuwe potgrond en zo nodig van een grotere maat pot. Als u de fluweelplant niet snoeit, worden zijn takken steeds langer. Oudere exemplaren worden vaak minder mooi paars van kleur. U kunt de plant gemakkelijk verjongen door stekken te nemen en die met enkele exemplaren bij elkaar in stekgrond te zetten of te laten wortelen op water voor u ze in een nieuwe pot plaatst. Top de stekken een aantal keren om ze te laten vertakken.', 'MODERATE', 'fluweelplant.jpg', 'MONTH', 'Gunura Aurantiaca', 'SUNNY', 'uploads/fluweelplant.jpg', 'Fluweelplant', 'novi@mail.com', '2021-10-01 11:32:44.084', 'TWODAYS');

INSERT INTO Plants (id, description, care, potting, difficulty, file_name, food, latin_name, light, location, name, uploaded_by_username, uploaded_date, watering)
VALUES ('1007',  'De Alocasia is een kamerplant die je niet zo snel over het hoofd zal zien. Deze namen heeft de Alocasia te danken aan zijn enorme bladeren (olifantenoren) die wel 1 meter groot kunnen worden. Het is gelukkig ook niet de moeilijkste plant om te verzorgen.','De Alocasia staat graag op een plek met veel zonlicht. Bij een gebrek aan zonlicht zullen de bladeren lange stengels krijgen. Hiermee probeert de kamerplant het zonlicht te bereiken. Worden de bladeren te lang, dan kan een Alocasia het gewicht van de enorme bladeren niet meer dragen en is er een kans dat deze gaan hangen of zelfs breken. De Olifantsoor groeit van nature naar de zon toe, draai de plant daarom met enige regelmaat een kwartslag.','De Alocasia groeit relatief snel. Hierdoor is regelmatig verpotten noodzakelijk. Het verpotten zorgt voor nieuwe voedingsstoffen, luchtigere grond en meer ruimte voor wortelgroei. Maar het belangrijkste is dat er voldoende aarde aanwezig moet zijn om vocht op te nemen.  Gebruik  een plantenbak met een diameter van minimaal twintig procent meer dan de vorige. Doe dit met gewone universele potgrond en probeer zo min mogelijk wortels te beschadigen.', 'EASY', 'Alocasia.jpeg', 'MONTH', 'Alocasia', 'SUNNY', 'uploads/Alocasia.jpeg', 'Oliefantsoor', 'novi@mail.com', '2021-10-01 11:40:44.084', 'THREEDAYS');


INSERT INTO Plants (id, description, care, potting, difficulty, file_name, food, latin_name, light, location, name, uploaded_by_username, uploaded_date, watering)
VALUES ('1009',  'De Begonia is een kamerplant die makkelijk te stekken en te kruisen is. Hierdoor zijn er ontelbare soorten. Vele soorten zijn zelfs te vermeerderen door middel van een blad met een steeltje in de grond te steken.','De grond rondom een bloeiende Begonia of Bladbegonia dient ten alle tijden vochtig te zijn. Voel regelmatig aan de grond om te controleren of jouw Begonia niet aan het uitdrogen is. Plaats een bladbegonia op een locatie met halfschaduw. Vermijd daarom de felle middagzon, maar geef de plant wel voldoende indirect licht. Een locatie voor een raam op het noorden is daarom ideaal. Staat jouw raam op het zuiden? Plaats de bladbegonia dan enkele meters van het raam.','Wacht met verpotten totdat de pot vol zit met wortels. Dit kan je zien als je de plant uit de pot haalt. Pas als de wortels van de plant alle aarde vasthouden, is het tijd voor verpotten.
Het verpotten hoeft niet altijd in een grotere pot. Als een begonia verwelkt, Kan dit betekenen dat de wortels beginnen te rotten en dat er te veel aarde is en meer voedingsstoffen (en water) levert dan de plant nodig heeft. Verplaats de begonia dan naar een kleinere pot.', 'MODERATE', 'begonia.jpg', 'MONTH', 'Begonia', 'HALFSUNNY', 'uploads/begonia.jpg', 'Begonia', 'novi@mail.com', '2021-10-01 11:55:44.084', 'THREEDAYS');

INSERT INTO Plants (id, description, care, potting, difficulty, file_name, food, latin_name, light, location, name, uploaded_by_username, uploaded_date, watering)
VALUES ('1010',  'De Croton Codiaeum, is afkomstig uit Indonesië en India. De Croton is een ongelooflijk veelzijdige kamerplant, die iedereen betovert met zijn dikke, leerachtige bladeren. De bladeren hebben een glanzend oppervlak, in een grote verscheidenheid van kleuren. Van rood, geel, groen, oranje, crème, roze en zwart tot een combinatie van dit alles.','Het is belangrijk om de grond van de Croton altijd licht vochtig te houden. Je kan dit controleren door je pink in de grond te steken. Laat de Croton nooit uitdrogen. Ook niet in de winter! Het beste is om de Croton het hele jaar door één keer per week water te geven. Als de bladeren verwelken, is dat een teken van te veel water. Als de onderste bladeren afvallen, is dat een teken van te weinig water. Houd de grond vochtig, maar geef pas water als de bovenkant van de grond droog is.','De Croton staat graag op een plek met voldoende licht. Het beste is indirect zonlicht tot halfschaduw. De Croton geeft de voorkeur aan een plaats naast een raam op het westen of oosten. Een plekje bij het zuiden kan natuurlijk ook, maar zorg er wel voor dat de plant minstens 2 meter van het raam staat. Wij adviseren de Croton eens in de 2 jaar te verpotten, en wanneer de pot te klein wordt natuurlijk.', 'MODERATE', 'croton1.jpg', 'TWOWEEKS', 'Codiaeum', 'HALFSUNNY', 'uploads/croton1.jpg', 'Croton', 'novi@mail.com', '2021-10-05 11:55:44.084', 'WEEK');
INSERT INTO Plants (id, description, care, potting, difficulty, file_name, food, latin_name, light, location, name, uploaded_by_username, uploaded_date, watering)
VALUES ('1011',  'De Monstera heeft prachtige grote groene bladeren met gaten en je herkent de Monstera dan ook direct aan zijn opvallende uiterlijk. De Gatenplant heeft zijn naam te danken aan de gaten! Hij is niet alleen makkelijk in de verzorging, maar helpt ook nog eens mee om de lucht te zuiveren.','Tussen de gietbeurten door laat je de kluit bijna helemaal uitdrogen voor je weer water geeft. Deze plant in de lente en zomer één of twee keer per week water nodig en in de winter een keer per week. Blijf naar je planten kijken en pas de hoeveelheid water aan als je merkt dat de grond snel droog is of juist heel lang nat blijft.','Verpotten doe je op de volgende manier: Vul het onderste deel (ongeveer één derde deel) met de potgrond. Haal hem voorzichtig uit de oude pot. Inspecteer direct de plant op wortelrot of andere ziekten. Stekken: zet de afgeknipte tak in een glazen fles of potje. Vervang het water elke week om de stek van genoeg voedingsstoffen te voorzien. Na een aantal weken zullen de wortels vanzelf gaan groeien.', 'EASY', 'monstera.jpg', 'MONTH', 'Monstera', 'SHADOW', 'uploads/monstera.jpg', 'Gatenplant', 'novi@mail.com', '2021-10-02 11:55:44.084', 'WEEK');

INSERT INTO Plants (id, description, care, potting, difficulty, file_name, food, latin_name, light, location, name, uploaded_by_username, uploaded_date, watering)
VALUES ('1012',  'De cactus: een makkelijke en sterke huisgenoot die een tikkie stekelig over kan komen. Hij is verkrijgbaar in allerlei soorten en maten. Wist je dat de cactus van oorsprong bladeren heeft? Deze hebben zich opgerold om zo minder water nodig te hebben. Geef je cactus vooral niet teveel water, hij kan heel goed tegen droogte en juist slecht tegen teveel water.','De cactus groeit van nature langzaam, daarom verbruikt deze binnenplant weinig voeding. Bemesten is niet nodig in de winter en niet noodzakelijk in de herfst. Geef de cactus vloeibare voeding bij elke vierde keer water geven, of een vierde van de dosering welke staat aangegeven op de verpakking.','De beste periode om je cactussen te verpotten is tussen maart en mei, wanneer ze uit hun winterslaap ontwaken en nieuwe energie nodig hebben om te groeien. Geef je cactus enkele dagen voor het verpotten geen water meer zodat de wortelkluit bij het verpotten niet te vochtig is en de plant eenvoudiger uit de pot kan gehaald worden.', 'EASY', 'cactus.jpg', 'MONTH', 'Cactaceae', 'SUNNY', 'uploads/cactus.jpg', 'Cactus', 'novi@mail.com', '2021-10-03 11:55:44.084', 'MONTH');

INSERT INTO Plants (id, description, care, potting, difficulty, file_name, food, latin_name, light, location, name, uploaded_by_username, uploaded_date, watering)
VALUES ('1013',  'De Aloë Vera staat het liefst op een plek in de volle zon. Hier groeit de plant een stuk sneller! Let er wel op dat de aarde op deze plek sneller droog wordt. Hij mag hier dus wat vaker water hebben. In de halfschaduw doet de plant het ook goed, hier heeft hij wel minder water nodig.','In de herfst en de winter kan je de plant gerust een aantal weken droog laten staan. Het meest voorkomende probleem is te veel water geven, wat rotting veroorzaakt. Worden de punten van het blad een beetje rood en beginnen ze samen te trekken? Dan mag de plant wat meer water hebben.','De ondiepe wortels hebben geen diepe pot nodig. Een te diepe pot verhoogt het risico op water, wat rot kan veroorzaken. Je wil ook niet te veel aarde aan de zijkanten. De wortels van een aloë vera moeten ongeveer tweederde van de pot in beslag nemen en de rest moet als aarde worden gebruikt. De pot moet voldoende drainagegaten hebben. Zowel plastic als geglazuurde of ongeglazuurde klei zijn prima.', 'MODERATE', 'AloeSoorten.jpeg', 'MONTH', 'Aloë Vera', 'DIRECTSUN', 'uploads/AloeSoorten.jpeg', 'Aloë', 'novi@mail.com', '2021-10-03 11:56:45.084', 'WEEK');

INSERT INTO Plants (id, description, care, potting, difficulty, file_name, food, latin_name, light, location, name, uploaded_by_username, uploaded_date, watering)
VALUES ('1014',  'Veel cultivars hebben bonte bladeren met groene, paarse, rode, gele, witte en crème kleuren. De bloeiwijzen van bromelias zijn ook beschouwd als aanzienlijk diverser dan die van enige andere plantenfamilie. Sommige bloempieken kunnen een hoogte van 10 meter bereiken, terwijl anderen slechts bloemen hebben van enkele millimeters. Sommige bromelias zijn licht geurend terwijl anderen sterk geurend zijn','De plant houdt van een hoge luchtvochtigheid, maar hoeft niet elke dag opnieuw water te krijgen. Eén keer per week is voldoende. Het leuke van deze plant is dat je water in het kelkje in het midden kan gieten.','Je hoeft de Bromelia zelden tot nooit te verpotten. Dit komt doordat de rozet begint af te sterven zodra de bloemknop open gaat. Hoewel de plant hierna nog 1 of 2 jaar kan voortbestaan, is de levensduur dusdanig kort dat verpotten waarschijnlijk niet nodig is. Maar geen zorgen, het afsterven van de ouderplant hoeft niet het einde van jouw Bromelia te betekenen! Na de bloei ontstaan er namelijk stekjes.', 'MODERATE', 'BROMELIA.jpg', 'NEVER_SPECIAL', 'Bromeliaceae', 'HALFSUNNY', 'uploads/BROMELIA.jpg', 'Bromelia', 'novi@mail.com', '2021-10-03 11:52:43.084', 'THREEDAYS');

INSERT INTO Plants (id, description, care, potting, difficulty, file_name, food, latin_name, light, location, name, uploaded_by_username, uploaded_date, watering)
VALUES ('1015',  'Deze kamerplant is geliefd omdat hij zo veelzijdig is. Zo kun je kiezen voor klimplanten, maar ook voor staande planten die een stammetje vormen. Een klimplant als Philodendron is te koop in hangpotten als hangplant, maar wordt ook langs mosstokken en klimrekjes omhoog geleid','De Philodendron is een bekende kamerplant die goed te verzorgen is. De plant staat het liefst op een plek in de (half)schaduw. Zorg dat de grond lichtvochtig is, zonder dat de wortels in een laag water staan. Doordat deze kamerplant zo makkelijk is, in het onderhoud, is de plant in vele kantoren te vinden.','Oudere exemplaren hoeven niet per se verpot te worden. Hier kan je ook de losse bovenlaag vervangen met nieuwe verse grond. Het verpotten naar een nieuwe plantenbak is wel beter voor de plant.', 'EASY', 'drakenklimop.jpg', 'NEVER_SPECIAL', 'Philodendron', 'HALFSUNNY', 'uploads/drakenklimop.jpg', 'Drakenklimop', 'novi@mail.com', '2021-10-02 11:52:53.084', 'WEEK');

INSERT INTO Plants (id, description, care, potting, difficulty, file_name, food, latin_name, light, location, name, uploaded_by_username, uploaded_date, watering)
VALUES ('1016',  'Diverse soorten Ficussen sieren onze woonkamers en kantoren. Van oorsprong komt de Ficus uit Afrika, maar de plant komt ook voor in Zuid-Amerika, Australië en Azië. De Ficus behoort tot de plantenfamilie Moraceae, oftewel Moerbeifamilie. De Ficus is verkrijgbaar in diverse soorten, zoals een Ficus Lyrata met groot blad, Ficus Benjamina met klein blad of een Ficus Microcarpa die lijkt op een bonsaiboom.','De grond van een Ficus dient altijd licht vochtig te zijn, zonder dat de plant met zijn wortels in het water staat. Het is daarom verstandig om kleine hoeveelheden water per keer te geven. Geef de plant pas opnieuw water op het moment dat de grond droger begint aan te voelen. Vooral bij een nieuwe kamerplant is het van belang om in het begin regelmatig de vochtigheid te controleren, zodat het beter in te schatten is of de kamerplant de juiste hoeveelheid water krijgt.','Verpot de plant ongeveer elke 2 jaar. Doe dit eerder als de pot te klein wordt. Een Ficus groeit meestal sneller na het verpotten. Stel het verpotten een jaar uit, wanneer de kamerplant te groot wordt. Vermeerderen van een ficus kan eenvoudig door stekken. Dit kan zowel in vochtige turf en zand of in het water. Dit kan je doen door, in de lente, een kopstek van de plant af te knippen. Snoei een tak met minimaal 2 bladeren af van de plant.', 'MODERATE', 'ficus.jpg', 'YEAR', 'Ficus', 'SUNNY', 'uploads/ficus.jpg', 'Ficus', 'novi@mail.com', '2021-10-03 11:58:52.084', 'WEEK');

INSERT INTO Plants (id, description, care, potting, difficulty, file_name, food, latin_name, light, location, name, uploaded_by_username, uploaded_date, watering)
VALUES ('1008',  'Je herkent hem meteen, met zijn exotisch aandoende, grote schutblad, waarvan je bij het aanraken eigenlijk verwacht dat het van plastic is. Uit het schutblad, dat felrood, maar ook diverse tinten paars, roze, wit of zelfs groen kan hebben, komt de bloeikolf tevoorschijn. Dit is de bloem en bestaat uit een heleboel kleine bloemen van ongeveer 3 mm.','De anthurium verbruikt niet veel water, maar dient wel in continue licht vochtige grond te staan. In de wintermaanden mag de grond af en toe een beetje uitdrogen. Bij een wat grotere flamingoplant kan je de stam goed zien. Snijd of knip een stekje hiervan af en zet deze in het water. Deze plant is ook geschikt om in water te kweken.','Een Anthurium hoef je niet al te vaak te verpotten, meestal maar één keer per twee jaar. Je kunt dan voor een grotere pot gaan, of ervoor kiezen om de plant te verdelen. Dit is het gemakkelijkst als je je Anthurium toch al wilde verpotten. Als je de plant uit de pot haalt, zie je meestal dat deze eigenlijk uit meerdere aparte planten bestaat, aangezien de soort uitlopers produceert.', 'MODERATE', 'Anthurium2.jpg', 'TWOWEEKS', 'Anthurium', 'SUNNY', 'uploads/Anthurium2.jpg', 'Flamingoplant', 'novi@mail.com', '2021-10-02 11:45:44.084', 'THREEDAYS');




